name: random_quote_generator
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.2
  http: ^0.13.3  # Ensure this is included for API requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/author_image1.jpg
  - assets/images/author_image2.jpg
  - assets/images/author_image3.jpg
  - assets/images/author_image4.jpg
  - assets/images/author_image5.jpg
  - assets/images/author_image6.jpg
  - assets/images/author_image7.jpg
  - assets/images/author_image8.jpg
  - assets/images/author_image9.jpg
  - assets/images/author_image10.jpg
  - assets/images/author_image11.jpg
  - assets/images/author_image12.jpg  
  - assets/images/author_image13.jpg  
  - assets/images/author_image14.jpg 
  - assets/images/author_image15.jpg 
  - assets/images/author_image16.jpg 
  - assets/images/author_image17.jpg 
  - assets/images/background.jpg